<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="docs/icon.svg" />
  <title>Typst in Service worker</title>

  <script type="module">
  navigator.serviceWorker.register('/worker.js', {
    scope: '/',
    type: "module",
  }).then((s) => {
    s.update()
    window.workerStatus.appendChild(document.createTextNode("Worker registered"))
  }).catch((e) => {
    window.workerStatus.appendChild(document.createTextNode(e))
  });
  navigator.serviceWorker.getRegistration().then(reg => {
    if (reg) reg.update();
  });
  </script>
  <script type="module">
  if (!navigator.serviceWorker.controller) {
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      window.location.reload()
    })
  }
  </script>
</head>
<body>

    <h1>
          <img src="docs/icon.svg" style="height: 1em; width: 1em; vertical-align: top;" />
        Typst via Service Worker</h1>

 <span id="workerStatus"></span>

 <h2>Rendered as PDF</h2>
 <p>
     The PDF file linked below is compiled via Service worker and then served to you.
 </p>
 <p>
     <a href="docs/dynamic.pdf" target="_blank">Open PDF</a>
 </p>

 <h2>Rendered as SVG</h2>
 <p>Below you should see the document as SVG graphic generated and served the the Service Worker<p>
 <figure>
     <a href="docs/dynamic.svg" target="_blank">
     <img onerror="false && navigator.serviceWorker && setTimeout(window.location.reload.bind(window.location), 1000)" src="docs/dynamic.svg" alt="SVG rendered via typst in ServiceWorker" />
     </a>
 </figure>

 <h2>Favicon</h2>

 <p>
 The SVG favicon is also generated by the Service Worker and served as SVG
 </p>

</body>

</html>
