<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="docs/icon.typst.svg" />
  <title>Typst in Service worker</title>

  <script type="module">
  navigator.serviceWorker.register('./worker.js', {
    scope: './',
    type: "module",
  }).then((s) => {
    s.update()
    window.workerStatus.appendChild(document.createTextNode("Worker registered"))
    window.workerStatus.style.color = "darkgreen"
  }).catch((e) => {
    window.workerStatus.style.color = "darkred"
    window.workerStatus.appendChild(document.createTextNode("Registration failed"))
    window.workerStatus.appendChild(document.createTextNode(e))
  });
  navigator.serviceWorker.getRegistration().then(reg => {
    if (reg) reg.update();
  });
  </script>
  <script type="module">
  if (!navigator.serviceWorker.controller) {
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      window.location.reload()
    })
  }
  </script>
  <style>
  main {
      max-width: 50em;
      margin: auto;
      font-family: monospace;
  }
  </style>
</head>
<body>
<main>

    <h1>
          <img src="docs/icon.typst.svg" style="height: 1em; width: 1em; vertical-align: top;" />
        Typst via Service Worker</h1>

<p>
    This is an experiment for compiling <a href="https://typst.app/">typst</a> to PDF and to SVG on the client inside a Service Worker.
</p>
<p>
    The server can serve static (or dynamic) <code>.typst</code> files. A Service Worker acts as a proxy that detects if a PDF file is requested and rewrites the URL to the corresponding typst file (eg. by stripping the <code>.pdf</code> extension from the URL). It then waits for the plain text typst response, and feeds the typst code into the typst compiler running locally inside the Service Worker and then serve the result as PDF file back to the Browser window.
</p>

<p>
    For this to work the Service Worker has to be registered by loading this HTML page once.
</p>

 <span id="workerStatus"></span>

 <h2>Rendered as PDF</h2>
 <p>
     The PDF file linked below is compiled via Service worker and then served to you.
 </p>
 <p>
     <a href="docs/dynamic.typst.php.pdf" target="_blank">Open PDF</a> |
     <a href="docs/dynamic.typst.php" target="_blank">Open Typst Source</a>
 </p>

 <h2>Rendered as SVG</h2>
 <p>Below you should see the document as SVG graphic generated and served by the Service Worker.<p>
 <figure>
     <a href="docs/dynamic.typst.php.svg" target="_blank">
     <img width="200" src="docs/dynamic.typst.php.svg" alt="SVG rendered via typst in ServiceWorker" />
     </a>
 </figure>

 <h2>Favicon</h2>

 <p>

 The SVG <a href="docs/icon.typst.svg" target="_blank">favicon</a> of this page is also and SVG file generated by the Service Worker.
 </p>

</main>

</body>

</html>
